### ISSUE TITLE
老哥,似乎不能设置背景图片和关闭按钮的图片诶

### ISSUE THREAD

**Issue by eclipse4dk** [joelan/WeiboPopupMenu#1]
我在build后面执行这个操作.build().setmCloseButtomResourceid(R.drawable.unpressplus),报错说参数incompatible type,我看你demo里面关闭图片也是.png,可能背景是只能设置颜色属性,但是关闭按钮的图片不知道为什么会报incompatible type,求指导.

**Comment by joelan** [comment]
@eclipse4dk 是不能设置背景图片，没这个设置，只留了设置背景颜色，至于关闭图片，你先buid出来一个PopMenu对象再对这个对象操作setmCloseButtomResourceid就行，不能把PopMenu的执行方法返回赋给PopMenu变量，setmCloseButtomResourceid后返回值是void,这肯定类型不匹配。
