### ISSUE TITLE
不知道为何 弹出菜单时按返回键，会退出APP ，菜单不会消失

### ISSUE THREAD

**Issue by cuckooemm** [joelan/WeiboPopupMenu#4]

**Comment by joelan** [comment]
自己重写一下 onBackPressed 方法，调用一下菜单 的isShowing()方法判断是否在显示，显示的话就调用hide()方法，菜单没在显示，直接  super.onBackPressed()就行

**Comment by joelan** [comment]
自己重写一下 onBackPressed 方法，调用一下菜单 的isShowing()方法判断是否在显示，显示的话就调用hide()方法，菜单没在显示，直接 super.onBackPressed()就行
